//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 02:14:51 PM MESZ 
//


package profil;

import javax.xml.bind.annotation.XmlRegistry;
import profil.Profile.Profil;
import profil.Profile.Profil.Abos;
import profil.Profile.Profil.Abos.Genres;
import profil.Profile.Profil.Abos.Serien;
import profil.Profile.Profil.Filtercontainer;
import profil.Profile.Profil.Filtercontainer.Filter;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the profil package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: profil
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Genres }
     * 
     */
    public Genres createProfileProfilAbosGenres() {
        return new Genres();
    }

    /**
     * Create an instance of {@link Abos }
     * 
     */
    public Abos createProfileProfilAbos() {
        return new Abos();
    }

    /**
     * Create an instance of {@link Filtercontainer }
     * 
     */
    public Filtercontainer createProfileProfilFiltercontainer() {
        return new Filtercontainer();
    }

    /**
     * Create an instance of {@link profil.Profile.Profil.Filtercontainer.Filter.Genre }
     * 
     */
    public profil.Profile.Profil.Filtercontainer.Filter.Genre createProfileProfilFiltercontainerFilterGenre() {
        return new profil.Profile.Profil.Filtercontainer.Filter.Genre();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link Serien }
     * 
     */
    public Serien createProfileProfilAbosSerien() {
        return new Serien();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createProfileProfilFiltercontainerFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link profil.Profile.Profil.Abos.Genres.Genre }
     * 
     */
    public profil.Profile.Profil.Abos.Genres.Genre createProfileProfilAbosGenresGenre() {
        return new profil.Profile.Profil.Abos.Genres.Genre();
    }

    /**
     * Create an instance of {@link Profil }
     * 
     */
    public Profil createProfileProfil() {
        return new Profil();
    }

}
