/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.xml.bind.JAXBException;
import org.jivesoftware.smack.XMPPException;

/**
 *
 * @author Steveboo
 */
public class Filter extends javax.swing.JFrame {

    /**
     * Creates new form Filter
     */
    private Hauptmenue haupt;
    private XMPPController xmpp;
    public Filter(Hauptmenue haupt, XMPPController xmpp){
        this.xmpp = xmpp;
        this.haupt = haupt;
        initComponents();
        setVisible(true);
        
        availableSerieList.setModel(xmpp.refreshSubscibeList());
        filterList.setModel(xmpp.refreshFilterList());
        serienInFilterList.setModel(xmpp.refreshSerienInFilterList(filterList));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        filterList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        filterNameTextfield = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        serienInFilterList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        filterDeleteButton = new javax.swing.JButton();
        filterAddButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        availableSerieList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        filterSaveButton = new javax.swing.JButton();
        filterToMainButton = new javax.swing.JButton();
        serieEntfernenButton = new javax.swing.JButton();
        aktualisierenButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Filter Bearbeiten");

        filterList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(filterList);

        jLabel2.setText("Vorhandene Filter");

        serienInFilterList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(serienInFilterList);

        jLabel3.setText("Hinzugefügte Serien");

        filterDeleteButton.setText("Löschen");
        filterDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterDeleteButtonActionPerformed(evt);
            }
        });

        filterAddButton.setText("Hinzufügen");
        filterAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterAddButtonActionPerformed(evt);
            }
        });

        availableSerieList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(availableSerieList);

        jLabel4.setText("Weitere Serien Hinzufügen");

        filterSaveButton.setText("Neuer Filter");
        filterSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterSaveButtonActionPerformed(evt);
            }
        });

        filterToMainButton.setText("Hauptmenü");
        filterToMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterToMainButtonActionPerformed(evt);
            }
        });

        serieEntfernenButton.setText("Entfernen");
        serieEntfernenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieEntfernenButtonActionPerformed(evt);
            }
        });

        aktualisierenButton.setText("Aktualisieren");
        aktualisierenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktualisierenButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Filter Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filterDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)
                                .addComponent(aktualisierenButton))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(serieEntfernenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)
                                .addComponent(filterAddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterToMainButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filterSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filterToMainButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterAddButton)
                    .addComponent(filterDeleteButton)
                    .addComponent(serieEntfernenButton)
                    .addComponent(aktualisierenButton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterSaveButton)
                    .addComponent(filterNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filterDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterDeleteButtonActionPerformed

            xmpp.deleteFilter(filterList);
            filterList.setModel(xmpp.refreshFilterList());
    }//GEN-LAST:event_filterDeleteButtonActionPerformed

    private void filterToMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterToMainButtonActionPerformed
        this.dispose();
        haupt.setVisible(true);
    }//GEN-LAST:event_filterToMainButtonActionPerformed

    private void aktualisierenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktualisierenButtonActionPerformed
        serienInFilterList.setModel(xmpp.refreshSerienInFilterList(filterList));
    }//GEN-LAST:event_aktualisierenButtonActionPerformed

    private void serieEntfernenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieEntfernenButtonActionPerformed
        xmpp.deleteSerieFromFilter(serienInFilterList);
        xmpp.refreshSerienInFilterList(filterList);
    }//GEN-LAST:event_serieEntfernenButtonActionPerformed

    private void filterAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterAddButtonActionPerformed
       xmpp.addSerieToFilter(availableSerieList);
       xmpp.refreshSerienInFilterList(filterList);
    }//GEN-LAST:event_filterAddButtonActionPerformed

    private void filterSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterSaveButtonActionPerformed
        xmpp.filterAdd(filterNameTextfield);
        xmpp.refreshFilterList();
    }//GEN-LAST:event_filterSaveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aktualisierenButton;
    private javax.swing.JList availableSerieList;
    private javax.swing.JButton filterAddButton;
    private javax.swing.JButton filterDeleteButton;
    private javax.swing.JList filterList;
    private javax.swing.JTextField filterNameTextfield;
    private javax.swing.JButton filterSaveButton;
    private javax.swing.JButton filterToMainButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton serieEntfernenButton;
    private javax.swing.JList serienInFilterList;
    // End of variables declaration//GEN-END:variables
}
