/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.xml.bind.JAXBException;
import org.jivesoftware.smack.XMPPException;

/**
 *
 * @author Steveboo
 */
public class Hauptmenue extends javax.swing.JFrame {

    /**
     * Creates new form Hauptmenue
     */
    private XMPPController xmpp;
    private Login login;
    private Abos abos;
    private Filter filter;
    private SerieFenster serie;
    private Profil profil;
    private SerieInfo serieInfo;
    public Hauptmenue(XMPPController xmpp, Login login) {
        this.login = login;
        this.xmpp = xmpp;
        initComponents();
        setVisible(true);

            filterButton1.setText(xmpp.getFilterName(0));
            filterButton2.setText(xmpp.getFilterName(1));
            nachrichtenListe.setModel(xmpp.refreshNachrichtenList());
            xmpp.gibNachrichtenListe(nachrichtenListe);
          
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        editAbosButton = new javax.swing.JButton();
        editFilterButton = new javax.swing.JButton();
        abmeldenButton = new javax.swing.JButton();
        editSerienButton = new javax.swing.JButton();
        editProfilButton = new javax.swing.JButton();
        serienInfosButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        nachrichtenListe = new javax.swing.JList();
        filterButton1 = new javax.swing.JButton();
        filterButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Startseite");

        editAbosButton.setText("Abos Bearbeiten");
        editAbosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAbosButtonActionPerformed(evt);
            }
        });

        editFilterButton.setText("Filter Bearbeiten");
        editFilterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editFilterButtonActionPerformed(evt);
            }
        });

        abmeldenButton.setText("Abmelden");
        abmeldenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abmeldenButtonActionPerformed(evt);
            }
        });

        editSerienButton.setText("Serien Bearbeiten");
        editSerienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSerienButtonActionPerformed(evt);
            }
        });

        editProfilButton.setText("Profil Bearbeiten");
        editProfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProfilButtonActionPerformed(evt);
            }
        });

        serienInfosButton.setText("Serien Infos");
        serienInfosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serienInfosButtonActionPerformed(evt);
            }
        });

        nachrichtenListe.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(nachrichtenListe);

        filterButton1.setText("Filter1");
        filterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton1ActionPerformed(evt);
            }
        });

        filterButton2.setText("Filter2");
        filterButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filterButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abmeldenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editSerienButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editFilterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editAbosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editProfilButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serienInfosButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filterButton2)
                    .addComponent(filterButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(editAbosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editFilterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editSerienButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editProfilButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serienInfosButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(abmeldenButton))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abmeldenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abmeldenButtonActionPerformed
        this.dispose();
        xmpp.disconnect();
        login.setVisible(true);

    }//GEN-LAST:event_abmeldenButtonActionPerformed

    private void editAbosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAbosButtonActionPerformed
        this.setVisible(false);
        abos = new Abos(this, xmpp);
    }//GEN-LAST:event_editAbosButtonActionPerformed

    private void editFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editFilterButtonActionPerformed
        this.setVisible(false);
        filter = new Filter(this, xmpp);
        
    }//GEN-LAST:event_editFilterButtonActionPerformed

    private void editSerienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSerienButtonActionPerformed
        this.setVisible(false);
        serie = new SerieFenster(this, xmpp);
    }//GEN-LAST:event_editSerienButtonActionPerformed

    private void editProfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProfilButtonActionPerformed
        this.setVisible(false);
        profil = new Profil(this, xmpp);

    }//GEN-LAST:event_editProfilButtonActionPerformed

    private void serienInfosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serienInfosButtonActionPerformed
        this.setVisible(false);
        serieInfo = new SerieInfo(this, xmpp);
    }//GEN-LAST:event_serienInfosButtonActionPerformed

    private void filterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton1ActionPerformed
        
        xmpp.filter1Button(xmpp.getFilterName(0));
    }//GEN-LAST:event_filterButton1ActionPerformed

    private void filterButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButton2ActionPerformed
       xmpp.filter1Button(xmpp.getFilterName(1));
    }//GEN-LAST:event_filterButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abmeldenButton;
    private javax.swing.JButton editAbosButton;
    private javax.swing.JButton editFilterButton;
    private javax.swing.JButton editProfilButton;
    private javax.swing.JButton editSerienButton;
    private javax.swing.JButton filterButton1;
    private javax.swing.JButton filterButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList nachrichtenListe;
    private javax.swing.JButton serienInfosButton;
    // End of variables declaration//GEN-END:variables
}
