/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

import org.jivesoftware.smack.XMPPException;

/**
 * 
 * @author Steveboo
 */
public class Hauptmenue extends javax.swing.JFrame {

	/**
	 * Creates new form Hauptmenue
	 */
	private Xmpptest xmpp;
	private Login login;
	private Abos abos;
	private Filter filter;
	private Serie serie;
	private Profil profil;
	private SerieInfo serieInfo;

	public Hauptmenue(Xmpptest xmpp, Login login) {
		this.login = login;
		this.xmpp = xmpp;
		initComponents();
		setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jScrollPane2 = new javax.swing.JScrollPane();
		jList2 = new javax.swing.JList();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList3 = new javax.swing.JList();
		editAbosButton = new javax.swing.JButton();
		editFilterButton = new javax.swing.JButton();
		abmeldenButton = new javax.swing.JButton();
		editSerienButton = new javax.swing.JButton();
		editProfilButton = new javax.swing.JButton();
		serienInfosButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Startseite");

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		jTabbedPane1.addTab("Filter 1", jScrollPane1);

		jList2.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(jList2);

		jTabbedPane1.addTab("Filter 2", jScrollPane2);

		jList3.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5", "6", "7", "8", "9", "10", "11", "12", "13", "14" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(jList3);

		jTabbedPane1.addTab("Filter 3", jScrollPane3);

		editAbosButton.setText("Abos Bearbeiten");
		editAbosButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editAbosButtonActionPerformed(evt);
			}
		});

		editFilterButton.setText("Filter Bearbeiten");
		editFilterButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editFilterButtonActionPerformed(evt);
			}
		});

		abmeldenButton.setText("Abmelden");
		abmeldenButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				abmeldenButtonActionPerformed(evt);
			}
		});

		editSerienButton.setText("Serien Bearbeiten");
		editSerienButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editSerienButtonActionPerformed(evt);
			}
		});

		editProfilButton.setText("Profil Bearbeiten");
		editProfilButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				editProfilButtonActionPerformed(evt);
			}
		});

		serienInfosButton.setText("Serien Infos");
		serienInfosButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						serienInfosButtonActionPerformed(evt);
					}
				});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jTabbedPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		278,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						abmeldenButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						editSerienButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						125,
																						Short.MAX_VALUE)
																				.addComponent(
																						editFilterButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						editAbosButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						editProfilButton,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						serienInfosButton,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)))
												.addComponent(jLabel1))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														jTabbedPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														218,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(23, 23,
																		23)
																.addComponent(
																		editAbosButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		editFilterButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		editSerienButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		editProfilButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		serienInfosButton)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addComponent(
																		abmeldenButton)))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void abmeldenButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_abmeldenButtonActionPerformed
		this.dispose();
		xmpp.disconnect();
		login.setVisible(true);

	}// GEN-LAST:event_abmeldenButtonActionPerformed

	private void editAbosButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editAbosButtonActionPerformed
		this.setVisible(false);
		abos = new Abos(this, xmpp);
	}// GEN-LAST:event_editAbosButtonActionPerformed

	private void editFilterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editFilterButtonActionPerformed
		this.setVisible(false);
		filter = new Filter(this, xmpp);
	}// GEN-LAST:event_editFilterButtonActionPerformed

	private void editSerienButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editSerienButtonActionPerformed
		this.setVisible(false);
		serie = new Serie(this, xmpp);
	}// GEN-LAST:event_editSerienButtonActionPerformed

	private void editProfilButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editProfilButtonActionPerformed
		this.setVisible(false);
		profil = new Profil(this, xmpp);
	}// GEN-LAST:event_editProfilButtonActionPerformed

	private void serienInfosButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serienInfosButtonActionPerformed
		this.setVisible(false);
		serieInfo = new SerieInfo(this, xmpp);
	}// GEN-LAST:event_serienInfosButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton abmeldenButton;
	private javax.swing.JButton editAbosButton;
	private javax.swing.JButton editFilterButton;
	private javax.swing.JButton editProfilButton;
	private javax.swing.JButton editSerienButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList jList1;
	private javax.swing.JList jList2;
	private javax.swing.JList jList3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JButton serienInfosButton;
	// End of variables declaration//GEN-END:variables
}
