/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

import restfulwebservice.ProfileService;

/**
 *
 * @author Steveboo
 */
public class Profil extends javax.swing.JFrame {

    /**
     * Creates new form Profil
     */
   private Hauptmenue haupt;
   private Xmpptest xmpp;
    public Profil(Hauptmenue haupt, Xmpptest xmpp) {
        this.haupt = haupt;
        this.xmpp = xmpp;
        initComponents();
        setVisible(true);
        profilBeschreibungTextfeld.setText(xmpp.getProfilBeschreibung());
        profilbildTextfeld.setText(xmpp.getProfilbild());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        profilbildTextfeld = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profilBeschreibungTextfeld = new javax.swing.JTextArea();
        profilSaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        profilToMainButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Profilbild");

        jLabel3.setText("Beschreibung");

        profilBeschreibungTextfeld.setColumns(20);
        profilBeschreibungTextfeld.setRows(5);
        jScrollPane1.setViewportView(profilBeschreibungTextfeld);

        profilSaveButton.setText("Speichern");
        profilSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilSaveButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Profil Bearbeiten");

        profilToMainButton.setText("Hauptmenü");
        profilToMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilToMainButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(profilSaveButton)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(profilbildTextfeld, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profilToMainButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(profilToMainButton))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6))
                    .addComponent(profilbildTextfeld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profilSaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profilToMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilToMainButtonActionPerformed
        this.dispose();
        haupt.setVisible(true);
    }//GEN-LAST:event_profilToMainButtonActionPerformed

    private void profilSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilSaveButtonActionPerformed
       
        xmpp.setProfil(profilBeschreibungTextfeld,profilbildTextfeld);
        
    }//GEN-LAST:event_profilSaveButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea profilBeschreibungTextfeld;
    private javax.swing.JButton profilSaveButton;
    private javax.swing.JButton profilToMainButton;
    private javax.swing.JTextField profilbildTextfeld;
    // End of variables declaration//GEN-END:variables
}
