/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

import javax.swing.JList;
import javax.swing.ListModel;


/**
 *
 * @author Steveboo
 */
public class SerieInfo extends javax.swing.JFrame {

    /**
     * Creates new form SerieInfo
     */
    private Hauptmenue haupt;
    private XMPPController xmpp;
    private String Serien_name;
    public SerieInfo(Hauptmenue haupt,XMPPController xmpp) {
        this.haupt = haupt;
        this.xmpp = xmpp;
        initComponents();
        setVisible(true);
        serienList.setModel(xmpp.refreshSerienList());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        serienList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        episodenList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        serienBeschreibungTextarea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        episodenBeschreibungTextarea = new javax.swing.JTextArea();
        serieInfoToMainButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        darstellerList = new javax.swing.JList();
        jScrollPane8 = new javax.swing.JScrollPane();
        darstellerBeschreibungTextarea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        aktualisierenButton = new javax.swing.JButton();
        darstellerAktualisierenButton = new javax.swing.JButton();
        episodenAktuaisierenButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Serien Infos");

        serienList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(serienList);

        jLabel2.setText("Serien Beschreibung");

        jScrollPane4.setViewportView(episodenList);

        jLabel3.setText("Episodenbeschreibung");

        serienBeschreibungTextarea.setColumns(20);
        serienBeschreibungTextarea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        serienBeschreibungTextarea.setRows(5);
        serienBeschreibungTextarea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        serienBeschreibungTextarea.setEnabled(false);
        jScrollPane2.setViewportView(serienBeschreibungTextarea);

        episodenBeschreibungTextarea.setColumns(20);
        episodenBeschreibungTextarea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        episodenBeschreibungTextarea.setRows(5);
        episodenBeschreibungTextarea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        episodenBeschreibungTextarea.setEnabled(false);
        jScrollPane3.setViewportView(episodenBeschreibungTextarea);

        serieInfoToMainButton.setText("Hauptmenü");
        serieInfoToMainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieInfoToMainButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Darsteller");

        jScrollPane7.setViewportView(darstellerList);

        darstellerBeschreibungTextarea.setColumns(20);
        darstellerBeschreibungTextarea.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        darstellerBeschreibungTextarea.setRows(5);
        darstellerBeschreibungTextarea.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        darstellerBeschreibungTextarea.setEnabled(false);
        jScrollPane8.setViewportView(darstellerBeschreibungTextarea);

        jLabel6.setText("Darsteller Beschreibung");

        aktualisierenButton.setText("Serien Aktualisieren");
        aktualisierenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktualisierenButtonActionPerformed(evt);
            }
        });

        darstellerAktualisierenButton.setText("Darsteller Aktualisieren");
        darstellerAktualisierenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darstellerAktualisierenButtonActionPerformed(evt);
            }
        });

        episodenAktuaisierenButton.setText("Episoden Aktualisieren");
        episodenAktuaisierenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                episodenAktuaisierenButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Episodenliste");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(serieInfoToMainButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aktualisierenButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(darstellerAktualisierenButton)
                        .addGap(18, 18, 18)
                        .addComponent(episodenAktuaisierenButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(serieInfoToMainButton)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(jScrollPane8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addComponent(jScrollPane1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktualisierenButton)
                    .addComponent(darstellerAktualisierenButton)
                    .addComponent(episodenAktuaisierenButton))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void serieInfoToMainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieInfoToMainButtonActionPerformed
     this.dispose();
     haupt.setVisible(true);
        
    }//GEN-LAST:event_serieInfoToMainButtonActionPerformed

    private void aktualisierenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktualisierenButtonActionPerformed
        Serien_name = xmpp.selectedSerie(serienList);
        serienBeschreibungTextarea.setText(xmpp.getSerienBeschreibung(Serien_name));
        darstellerList.setModel(xmpp.refreshDarstellerList());
        episodenList.setModel(xmpp.refreshEpisodenList());
      
    }//GEN-LAST:event_aktualisierenButtonActionPerformed

    private void darstellerAktualisierenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darstellerAktualisierenButtonActionPerformed
       String selectedDarsteller = xmpp.selectedDarsteller(darstellerList);
       String selectedSerie = xmpp.selectedSerie(serienList);
        darstellerBeschreibungTextarea.setText(xmpp.getDarstellerBeschreibung(selectedDarsteller,selectedSerie));

    }//GEN-LAST:event_darstellerAktualisierenButtonActionPerformed

    private void episodenAktuaisierenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodenAktuaisierenButtonActionPerformed
        String selectedSerie = xmpp.selectedSerie(serienList);
        episodenBeschreibungTextarea.setText(xmpp.getEpisodenBeschreibung(selectedSerie,episodenList,Serien_name));
    }//GEN-LAST:event_episodenAktuaisierenButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aktualisierenButton;
    private javax.swing.JButton darstellerAktualisierenButton;
    private javax.swing.JTextArea darstellerBeschreibungTextarea;
    private javax.swing.JList darstellerList;
    private javax.swing.JButton episodenAktuaisierenButton;
    private javax.swing.JTextArea episodenBeschreibungTextarea;
    private javax.swing.JList episodenList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JButton serieInfoToMainButton;
    private javax.swing.JTextArea serienBeschreibungTextarea;
    public javax.swing.JList serienList;
    // End of variables declaration//GEN-END:variables
}
