/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package xmppprojekt;

/**
 * 
 * @author Steveboo
 */
public class SerieInfo extends javax.swing.JFrame {

	/**
	 * Creates new form SerieInfo
	 */
	private Hauptmenue haupt;
	private Xmpptest xmpp;

	public SerieInfo(Hauptmenue haupt, Xmpptest xmpp) {
		this.haupt = haupt;
		this.xmpp = xmpp;
		initComponents();
		setVisible(true);
		serienList.setModel(xmpp.refreshSerienList());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane5 = new javax.swing.JScrollPane();
		jTextArea3 = new javax.swing.JTextArea();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		serienList = new javax.swing.JList();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jList3 = new javax.swing.JList();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTextArea4 = new javax.swing.JTextArea();
		serieInfoToMainButton = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jScrollPane8 = new javax.swing.JScrollPane();
		jTextArea5 = new javax.swing.JTextArea();
		jScrollPane9 = new javax.swing.JScrollPane();
		jTextArea6 = new javax.swing.JTextArea();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();

		jTextArea3.setColumns(20);
		jTextArea3.setRows(5);
		jScrollPane5.setViewportView(jTextArea3);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Serien Infos");

		serienList.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(serienList);

		jLabel2.setText("Serien Beschreibung");

		jList3.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "1.1 Der Winter Naht",
					"1.2 Der Winter ist da", "1.3 Der Winter bleibt",
					"2.1 Sommer auf Hawaii" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane4.setViewportView(jList3);

		jLabel3.setText("Episodenbeschreibung");

		jLabel4.setText("Datum");

		jTextArea1.setColumns(20);
		jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea1.setRows(5);
		jTextArea1
				.setText("Lorem Ipsum, Lorem Ipsum, Lorem Ipsum\nLorem Ipsum, Lorem Ipsum, Lorem Ipsum\nLorem Ipsum, Lorem Ipsum, Lorem Ipsum");
		jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		jTextArea1.setEnabled(false);
		jScrollPane2.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea2.setRows(5);
		jTextArea2
				.setText("Bla Bla Bla Lorem IpsumLore\nLorem IpsumLorem IpsumLorem Ipsum\nLorem IpsumLorem IpsumLorem Ipsum");
		jTextArea2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		jTextArea2.setEnabled(false);
		jScrollPane3.setViewportView(jTextArea2);

		jTextArea4.setColumns(20);
		jTextArea4.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea4.setRows(1);
		jTextArea4.setText("12.12.2012");
		jTextArea4.setAutoscrolls(false);
		jTextArea4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		jTextArea4.setEnabled(false);
		jScrollPane6.setViewportView(jTextArea4);

		serieInfoToMainButton.setText("Hauptmenü");
		serieInfoToMainButton
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						serieInfoToMainButtonActionPerformed(evt);
					}
				});

		jLabel5.setText("Darsteller");

		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Darsteller 1", "Darsteller 2", "Darsteller 3" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane7.setViewportView(jList1);

		jTextArea5.setColumns(20);
		jTextArea5.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea5.setRows(5);
		jTextArea5.setText("Super Darsteller");
		jTextArea5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		jTextArea5.setEnabled(false);
		jScrollPane8.setViewportView(jTextArea5);

		jTextArea6.setColumns(20);
		jTextArea6.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
		jTextArea6.setRows(1);
		jTextArea6.setDisabledTextColor(new java.awt.Color(0, 0, 0));
		jTextArea6.setEnabled(false);
		jScrollPane9.setViewportView(jTextArea6);

		jLabel6.setText("Darsteller Beschreibung");

		jLabel7.setText("Bild URL");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(
														jScrollPane1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														170,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(7, 7, 7)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jScrollPane4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		156,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane3)
																				.addComponent(
																						jScrollPane6)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel4))
																								.addGap(0,
																										0,
																										Short.MAX_VALUE))))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						238,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel2))
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						151,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						jLabel5))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(0,
																										0,
																										Short.MAX_VALUE)
																								.addComponent(
																										serieInfoToMainButton))
																				.addComponent(
																						jScrollPane8,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						260,
																						Short.MAX_VALUE)
																				.addComponent(
																						jScrollPane9)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														jLabel6)
																												.addComponent(
																														jLabel7))
																								.addGap(0,
																										0,
																										Short.MAX_VALUE)))))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(
																		serieInfoToMainButton)
																.addGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel6)
																				.addComponent(
																						jLabel5)))
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(
																		jLabel1)
																.addComponent(
																		jLabel2)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jScrollPane2)
																				.addComponent(
																						jScrollPane7)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jScrollPane8,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										166,
																										Short.MAX_VALUE)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jLabel7)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jScrollPane9,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel3)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jScrollPane3,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										100,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jLabel4)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addComponent(
																										jScrollPane6,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(27,
																										27,
																										27))
																				.addComponent(
																						jScrollPane4)))
												.addComponent(jScrollPane1))
								.addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void serieInfoToMainButtonActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_serieInfoToMainButtonActionPerformed
		this.dispose();
		haupt.setVisible(true);
	}// GEN-LAST:event_serieInfoToMainButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JList jList1;
	private javax.swing.JList jList3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JScrollPane jScrollPane9;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextArea jTextArea3;
	private javax.swing.JTextArea jTextArea4;
	private javax.swing.JTextArea jTextArea5;
	private javax.swing.JTextArea jTextArea6;
	private javax.swing.JButton serieInfoToMainButton;
	private javax.swing.JList serienList;
	// End of variables declaration//GEN-END:variables
}
